export const cmsRoutes = [
  {
    file: "/Static_html/path1/1. Why MBA.html",
    path: "why-mba",
  },
  {
    file: "/Static_html/path1/2. MBA or PGDM.html",
    path: "mba-pgdm",
  },
  {
    file: "/Static_html/path1/3. Admission Process.html",
    path: "admission-process",
  },
  {
    file: "/Static_html/path1/4. MBA Specialisations.html",
    path: "mba-specialization",
  },
  {
    file: "/Static_html/path1/5. Online MBA.html",
    path: "online-mba",
  },
  {
    file: "/Static_html/path1/6. Executive MBA.html",
    path: "executive-mba",
  },
  {
    file: "/Static_html/path1/7. Distance MBA.html",
    path: "distance-mba",
  },
  {
    file: "/Static_html/path1/8. Integrated MBA.html",
    path: "integrated-mba",
  },
  {
    file: "/Static_html/path1/9. Part Time MBA.html",
    path: "part-time-mba",
  },
  {
    file: "/Static_html/path1/9. Telecom.html",
    path: "telecom",
  },
  {
    file: "/Static_html/path1/9. wow.html",
    path: "more-courses",
  },
  {
    file: "/Static_html/path2/2. Marketing Management.html",
    path: "mba-in-marketing",
  },
  {
    file: "/Static_html/path2/3. Finance Management.html",
    path: "mba-in-finance",
  },
  {
    file: "/Static_html/path2/4. HR Management.html",
    path: "mba-in-hr",
  },
  {
    file: "/Static_html/path2/6. Operations Management.html",
    path: "mba-in-operations",
  },
  {
    file: "/Static_html/path2/9. International Business.html",
    path: "mba-in-ib",
  },
  {
    file: "/Static_html/path2/10. Business Analytics.html",
    path: "mba-in-ba",
  },
  {
    file: "/Static_html/path2/5. Rural Management.html",
    path: "mba-in-rm",
  },
  {
    file: "/Static_html/path2/7. Healthcare Management.html",
    path: "mba-in-hc",
  },
  {
    file: "/Static_html/path2/26. Banking _ Finance.html",
    path: "mba-in-bf",
  },
  {
    file: "/Static_html/path2/1. MBA Specialisation.html",
    path: "mba-more-specialisations",
  },
  {
    file: "/Static_html/path3/CAT 2022.html",
    path: "cat-2022",
  },
  { file: "5. Rural Management.html", path: "" },
  { file: "6. Operations Management.html", path: "" },
  { file: "7. Healthcare Management.html", path: "" },
  { file: "8. Supply Chain _ Logistics Management.html", path: "" },
  { file: "9. International Business.html", path: "" },
  { file: "10. Business Analytics.html", path: "" },
  { file: "11. Agri-Business.html", path: "" },
  { file: "12. Information Technology.html", path: "" },
  { file: "13. Entrepreneurship.html", path: "" },
  { file: "14. Infrastructure.html", path: "" },
  { file: "15. Corporate Social Responsibility.html", path: "" },
  { file: "16. Energy.html", path: "" },
  { file: "17. Digital Marketing.html", path: "" },
  { file: "18. Import _ Export.html", path: "" },
  { file: "19. Advertising _ Communication.html", path: "" },
  { file: "20. Pharmaceutical Management.html", path: "" },
  { file: "21. Oil _ Gas.html", path: "" },
  { file: "22. Sports Management.html", path: "" },
  { file: "23. Retail.html", path: "" },
  { file: "24. Telecom.html", path: "" },
  { file: "25. Textile.html", path: "" },
  { file: "26. Banking _ Finance.html", path: "" },
  { file: "27. Family Business.html", path: "" },
  { file: "28. Event.html", path: "" },
  { file: "30. Aviation.html", path: "" },
  { file: "31. Fashion Design.html", path: "" },
  { file: "1. MBA Specialisation.html", path: "" },
  { file: "2. Marketing Management.html", path: "" },
  { file: "3. Finance Management.html", path: "" },
  { file: "4. HR Management.html", path: "" },
  { file: "/Static_html/path3/1. CAT 2022.html", path: "cat-2022" },
  { file: "/Static_html/path3/2. XAT 2023.html", path: "xat-2023" },
  { file: "/Static_html/path3/3. NMAT 2022.html", path: "nmat-2022" },
  {
    file: "/Static_html/path3/4. CMAT 2023 - Incomplete.html",
    path: "cmat-2023",
  },
  { file: "/Static_html/path3/5. MAT - Incomplete.html", path: "mat" },
  { file: "/Static_html/path3/6. SNAP 2022.html", path: "snap-2022" },
  { file: "/Static_html/path3/7. ATMA.html", path: "atma" },
  { file: "/Static_html/path3/8. IBSAT 2022.html", path: "ibsat" },
  { file: "/Static_html/path3/9. IIFT.html", path: "iift" },
  { file: "/Static_html/path3/10. MAH CET.html", path: "mah-cet" },
  { file: "/Static_html/path3/11. IRMASAT 2023.html", path: "irmasat-2023" },
  { file: "/Static_html/path3/12. MICAT 2023.html", path: "micat-2023" },
  { file: "/Static_html/path3/13. TISSNET 2023.html", path: "tissnet-2023" },
  { file: "/Static_html/path3/14. GMAT.html", path: "gmat" },
];
